### ISSUE TITLE
Exception in Backtracking with Forward Checking

### ISSUE THREAD

**Issue by Lance-Inman** [Lance-Inman/project-1#1]
The following exception was thrown when trying to solve a graph of size 50 with 3 colors using Backtracking with Forward Checking.

> g
> graph size:50
> s
> Choose a solver (Min-conflicts, Simple-backtracking, backtracking-Fc, Backtracking-mac, Genetic:
> f
> Exception in thread "main" java.util.ConcurrentModificationException
>     at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
>     at java.util.ArrayList$Itr.next(ArrayList.java:831)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:34)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.fcBacktrack(FCBacktrack.java:44)
>     at src.FCBacktrack.solve(FCBacktrack.java:21)
>     at src.GraphColorer.main(GraphColorer.java:75)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:606)
>     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by shricep** [comment]
K. Is the line it's thrown on in a for-each loop?

**Comment by Lance-Inman** [comment]
FCBacktrack.java:44: Graph result = fcBacktrack(g); //continues the coloring at the next vertex
FCBacktrack.java:21: return fcBacktrack(g);

```
private Graph fcBacktrack(Graph g)
{
    //checking if the assignment (graph coloring problem) is complete
    if(isColored(g))
        return g;

    //var <- Select-Unassigned-Variable(csp, assignment)
    Vertex currentVertex = g.getVertices().get(curVertex); //since this is simple backtracking, progression is done simply by iterating through the Graph's list of vertices

    //test each possible color at the vertex (which list comes from each Vertex's possible color list, the one that is trimmed by forward checking)
    for(Integer color : currentVertex.getPossibleColor())
    {
        //check if the color is valid in this spot
        if(checkColorOnNeighbors(color, currentVertex.getNeighbors()))
        {
            currentVertex.setColor(color); //sets the color of currentVertex to color
            incDecision(); //Decision was made to color the vertex. Count it.
            forwardCheck(currentVertex, color); //remove the selected color as a possiblility from all connected vertices
            curVertex++; //allows the coloring to move to the next vertex

            Graph result = fcBacktrack(g); //continues the coloring at the next vertex
            //return the result if there wasn't a failure
            if(result != null)
                return result;
            else
                curVertex--; //ensures curVertex is returned to what really is the current vertex. Problems would be caused without this line.
        }
        currentVertex.setColor(-1); //Uncolor the vertex. The color ended up not working.
        undoForwardCheck(currentVertex, color); //re-instate the previously removed color to neighbor verteces' list of possible colors
        incDecision(); //The decision was made to backtrack. Count it.
    }

    return null; //null signifies failure
}
```

**Comment by shricep** [comment]
Push your most recent changes and I'll work to debug on my end.

**Comment by Lance-Inman** [comment]
The most recent changes are pushed to the master branch.

**Comment by shricep** [comment]
Replace the for loop declaration on line 34 with this:
for(int i = 0; i < currentVertex.getPossibleColor().size(); i++)
        {
            Integer color = currentVertex.getPossibleColor().get(i);

**Comment by shricep** [comment]
There'll likely be a similar problem on the MAC backtrack, so I'd change
line 34 there as well
